### ISSUE TITLE
Fridge placement

### ISSUE THREAD

**Issue by birdilicious** [cclrobotics/lhr-mechanical#5]
This is a master ticket being used to track the tickets to solve the issue with the fridge placement:
The goal: change the position and height of the fridge in relation to the Overhead, Benchtop and Cabinet. 
- [ ] Make measurements and plan #6 
- [ ] Purchase parts/items #7 
- [ ] Cut the benchtop so to move the fridge on Y axis #8 
- [ ] Build the new fridge platform #9
